### ISSUE TITLE
Constants cleanup on reload

### ISSUE THREAD

**Issue by baraabourghli** [baraabourghli/constantizer#10]

**Comment by faizalzakaria** [comment]
I just realized the reload option only for dev/test environment. 

Since the constant variable is set on the Global constant, so if we do as such:

`toto.yml`
```
ABC: test
```

Then we change the file, remove the ABC and add new constant, `DEF`.
```
DEF:  test
```

Then you would have the `ABC` constant still globally. 

Regardless,
I doubt this feature is needed since we don't do reload option in production mode. 

Correct me if I'm wrong.

**Comment by baraabourghli** [comment]
@faizalzakaria you are correct :+1: it was intended for development mode.
